name: "Release"
on:
  release:
    types: [published]

jobs:
  ecad:
    env:
      # General
      revision: ${{ github.event.release.tag_name }}
      # CadQuery variables
      mcad_dir: src/lib/mcad
      # KiBot variables
      project: SixnavPrototype
      input: src
      output: out
      config: .kibot/release.kibot.yaml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # Build component 3D models with CadQuery
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install CadQuery
        run: |
          python -m pip install --upgrade pip
          pip install cadquery==2.2.0b0
      - name: Build models
        run: for f in ${{ env.config }}/m_*.py; do python "$f"; done
      # Run KiBot release tasks
      - name: Generate KiBot outputs
        uses: INTI-CMNB/KiBot@v2_k6
        with:
          config: ${{ env.config }}
          dir: ${{ env.output }}
          schema: ${{ env.input }}/${{ env.project }}.kicad_sch
          board: ${{ env.input }}/${{ env.project }}.kicad_pcb
      # Upload build to Github release
      - name: Upload release files
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ env.output }}/**/*
            ${{ env.input }}/${{ env.project }}.kicad_sch
            ${{ env.input }}/${{ env.project }}.kicad_pcb